### ISSUE TITLE
Automated Test Failure: testMultipleConfigEditHistory() Method Fails on some builds of the Cron Job Builds

### ISSUE THREAD

**Issue by vaisakhkannan** [OpenLiberty/liberty-tools-intellij#1173]
I found that many of the builds have failed due to the test `testMultipleConfigEditHistory()`, which is the only test failing in most builds.

I am attaching the video of the test failure

**Comment by anusreelakshmi934** [comment]
From some of the videos, I observed that the configuration is already in a selected state. Clicking elsewhere and then returning to the configuration will likely resolve the issue.

**Comment by turkeylurkey** [comment]
Stack trace:
```
GradleSingleModMPSIDProjectTest > testMultipleConfigEditHistory() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'Container' by '//div[@class='HeavyWeightWindow']//div[@class='MyList']' in 10s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getMyList(ProjectFrameFixture.java:338)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.selectConfigUsingToolbar(UIBotTestUtils.java:2198)
        at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.testMultipleConfigEditHistory(SingleModMPProjectTestCommon.java:939)
```

**Comment by turkeylurkey** [comment]
Happens in different test case Java files:
```
MavenSingleModMPProjectTest > testMultipleConfigEditHistory 
MavenSingleModMPSIDProjectTest > testMultipleConfigEditHistory 
MavenSingleModMPProjectTest > testMultipleConfigEditHistory 
GradleSingleModMPProjectTest > testMultipleConfigEditHistory
```

**Comment by anusreelakshmi934** [comment]
Created a ticket in intellij-ui-test-robot for tracking- https://github.com/JetBrains/intellij-ui-test-robot/issues/496
