### ISSUE TITLE
Hover on text: 'wrong' did not trigger a pop-up window to open in testQuickFixInServerXML() and testDiagnosticInServerXML()

### ISSUE THREAD

**Issue by anusreelakshmi934** [OpenLiberty/liberty-tools-intellij#1204]
java.lang.RuntimeException: Hover on text: 'wrong' did not trigger a pop-up window to open 
Caused by:
        com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT5S) for condition function (Failed to find 'Container' by '//div[@class='HeavyWeightWindow']//div[@class='JEditorPane']' in 5s) 

---
Last time bug was seen: March 6th, 5th, 3rd & 2nd 2025
Link to build: https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13564497339/job/38075762249?pr=1296
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13650621388/job/38158154182 
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13585344984/job/37978979473

**Comment by staicy123** [comment]
On further analysis, I found a few more similar issues as follows:

Test: testDiagnosticInServerEnv
Issue:
GradleSingleModLSTest > testDiagnosticInServerEnv() FAILED
java.lang.RuntimeException: Hover on text: NONE did not trigger a pop-up window to open
    at io.openliberty.tools.intellij.it.UIBotTestUtils.hoverInAppServerCfgFile(UIBotTestUtils.java:828)
    at io.openliberty.tools.intellij.it.SingleModLibertyLSTestCommon.testDiagnosticInServerEnv(SingleModLibertyLSTestCommon.java:339)
Cron Job Links:
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/11720288995/job/32645295570
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/11720288995/job/32645286928
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/11739624706/job/32704500579
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/11739624706/job/32704491343
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/12706931490/job/35420829095
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/12706931490/job/35421758332
Here, there are several cron jobs with the same error.
Instead of encountering:

java.lang.RuntimeException: Hover on text: 'wrong' did not trigger a pop-up window to open
I observed:

java.lang.RuntimeException: Hover on text: NONE did not trigger a pop-up window to open
when running testDiagnosticInServerEnv().

Analysis is still in progress.

**Comment by staicy123** [comment]
GradleSingleModLSTest > testQuickFixInServerXML() FAILED
    java.lang.RuntimeException: Hover on text: 'wrong' did not trigger a pop-up window to open
        at io.openliberty.tools.intellij.it.UIBotTestUtils.hoverForQuickFixInAppFile(UIBotTestUtils.java:893)
        at io.openliberty.tools.intellij.it.SingleModLibertyLSTestCommon.testQuickFixInServerXML(SingleModLibertyLSTestCommon.java:306)
Cron Job link:
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/12667843593/job/35302020393

**Comment by staicy123** [comment]
I am attaching videos for both bugs mentioned in this issue.
Both issues demonstrate that suggestions are not appearing as expected, which is causing the tests to fail.
https://github.com/user-attachments/assets/30a58f55-88dc-4f54-8609-c49c9d1f5481


https://github.com/user-attachments/assets/f88a15c9-cde4-49a8-9e02-282b2a1d2c2b

**Comment by staicy123** [comment]
The cron job failure you reported appears to be related to the LTI version 24.0.9 and Liberty Language Server version liberty-langserver:2.1.2. I attempted to replicate the issue locally using the same versions but was unable to do so, as the problem seems intermittent.

To further investigate, I checked the latest changes in both LTI and LSP4IJ repositories but did not find any issues directly related to the reported failure. Based on this, I suspect the issue may have been resolved in the newer Liberty Language Server version (liberty-langserver:2.2), which is being used in the latest builds.

I recommend monitoring the issue with the latest version of the language server, and should the failure recur, we can investigate it further. For now, it seems that the issue might not be present in the current build.

**Comment by vaisakhkannan** [comment]
Out of 20 build I ran today on windows , 1 build is having 2 failures and those are unique failure compared to other 19 builds

```
GradleSingleModLSTest > testDiagnosticInServerXML() FAILED
    java.lang.RuntimeException: Hover on text: wrong did not trigger a pop-up window to open
```

```
 GradleSingleModLSTest > testServerXMLNonFeatureHover() FAILED
    java.lang.RuntimeException: Hover on text: httpEndpoint did not trigger a pop-up window to open
```

Build link : https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/12985114191/job/36209316139

**Comment by staicy123** [comment]
Hi @turkeylurkey,

I have analyzed this issue based on the latest changes in the main branch and the cron job executions. However, I was unable to reproduce the issue in my testing. That said, as noted in Vaishak’s comment, he was able to reproduce the issue in one of the 20 builds executed.

As per our previous discussion, we had agreed to close the issue if it was not occurring in the latest build and reopen it if it reappeared. Given that Vaishak has encountered the issue again, could you please advise on the next steps?

Thanks

**Comment by TrevCraw** [comment]
Thank you @staicy123.

@dessina-devasia @vaisakhkannan Let's have the team keep an eye out for this failure on any PR or cron job build runs for the next week. We can discuss at the beginning of next sprint whether to keep open or close.

**Comment by dessina-devasia** [comment]
sure @TrevCraw

**Comment by vaisakhkannan** [comment]
I found similar error as shown in the image below

<img width="973" alt="Image" src="https://github.com/user-attachments/assets/8c7595cd-af42-4c57-80ef-0d5102e42ea0" />

build link : https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13650621388/job/38158140445

**Comment by vaisakhkannan** [comment]
I found that the issue mainly occurs in `Windows` builds, but it also happens on `Mac`. However, the probability of occurrence is higher on `Windows` than on Mac. See the issue description for details on the recent build link.

**Comment by vaisakhkannan** [comment]
I found that the issue mainly occurs on `Windows` machines. However, I couldn’t reproduce this issue on a physical Windows machine by running the test and manually as well. I did notice that when I ran the test on a `physical` Windows machine, the diagnostic did not appear quickly.

In our code, there is a `for-loop` that checks for the diagnostic up to `10` times. The test fails if the diagnostic is not found after the 10th iteration. When I tested it locally, the diagnostic appeared on the 4th, 5th, or sometimes the 6th iteration. To ensure all tests pass, I tried increasing the loop iterations from 10 to 15.

Additionally, I observed that in Liberty version 25.0.0.2, when hovering over the feature tag in the GHA build, some diagnostics appeared in the `ssl` tag. However, this is unrelated to the diagnostic for the `wrong` keyword. This is because, regardless of whether the `ssl` tag diagnostic appears, the test sometimes succeeds, meaning the diagnostic for the wrong keyword occasionally appears even when the `ssl` tag diagnostic is present.

**Comment by vaisakhkannan** [comment]
I found similar test failures in Windows builds due to diagnostics not appearing properly.

https://github.com/user-attachments/assets/6b2769d1-4e32-4019-b44e-e2807664c96d

**Comment by vaisakhkannan** [comment]
Hi @TrevCraw , 
I have added some print statements in the test to determine the number of iterations required to get the diagnostic in `server.xml`. On Windows machines, I noticed that sometimes it takes more than 10 iterations for the diagnostic to be published in the `server.xml` editor tab window.

I am sharing an example build for verification.

https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/13827901999/job/38686150023

<img width="1172" alt="Image" src="https://github.com/user-attachments/assets/4e10b010-e1b5-4993-850e-5b41d2d3b5cf" />

So, in the above build, I increased the loop count from `10` to `15`. However, in the test `testDiagnosticInServerXML`, it still took a total of 10 iterations to get the diagnostic.

For the test `testQuickFixInServerXML`, in addition to increasing the loop count from 10 to 15, I also increased the sleep duration from 2 seconds to 10 seconds. However, even with this change, it still took a total of 11 iterations to get the diagnostic for listing the quick fix.

**Comment by turkeylurkey** [comment]
Suggestion: force the test to fail so that you always get a movie. Run the test a few times and see if the red underline appears some time during an iteration. Then average out the time it takes for the message to appear. 

It seems really strange that 20 seconds is not long enough for the error to appear. And if you wait 10 iterations that is 200s. Do all the tests that use this method take multiple iterations? I would also suggest a wait shorter than 20s, maybe 10s. But also increase the iterations because we just want to make sure the message appears at all. Waiting less time should speed up some test cases.

This is harder but would be nice: have the robot click on the Language Servers console so you can watch the LS message traffic while the movie records the attempts to see the diagnostic (hover). The robot may also need to click to enable trace level logging before all this.

**Comment by vaisakhkannan** [comment]
https://github.com/user-attachments/assets/59306d23-4ee3-430f-ba28-477cc91eeff8

**Comment by turkeylurkey** [comment]
At the 0:28 mark we first try to hover. "Sending textDocument/hover" and "Received textDocument/hover" happens but IntelliJ does not render this info on the screen as a red underline. We try hover again multiple times but there are no more textDocument/hover messages sent or received. Then at 3:14 three seconds after a hover attempt (does not seem synchronized with robot, happens 2:46 after last typing in editor) we see textDocument/documentLink and textDocument/codeAction sent and received as well as workspace/configuration messages. Then the red underline appears, probably the info first sent at 0:28. But we don't see the hover text yet. On the next attempt, right after the mouse cursor waggles we get the hover text. 

Probably one of those messages caused IntelliJ to render the hover info. (In the second example only textDocument/documentLink is sent/received when the red underline appears.) If we suspect the problem is with IntelliJ it seems ok to try something to avoid this IntelliJ error. My idea is when we move the typing cursor to 1,1 on each iteration the robot should type <blank> and <backspace>, wait one second and then try the hover again. Normally I don't like to change the conditions in the editor because it basically invalidates the test but we could discuss this tomorrow.

**Comment by turkeylurkey** [comment]
Maybe make the robot type slower like 1 character per second. Then IntelliJ could keep up with the typing on a slow github action vm.
