### ISSUE TITLE
Liberty Project terminal not working with newer versions of IntelliJ IDEA IDE

### ISSUE THREAD

**Issue by evie-lau** [OpenLiberty/liberty-tools-intellij#143]
Related to the version bumps for supporting Java17 in PR #131.

Potentially two problems when using newer versions of IntelliJ IDE:
- Automatically opening up a dedicated terminal window(s) for the Liberty project(s) does not seem to work
- Running the dev commands via the Dashboard will open a new terminal, but cannot find the existing terminal when trying to stop.
![image](https://user-images.githubusercontent.com/689163/202559608-4811bf36-9b80-4c4a-82e9-26cef52e961e.png)

After some extensive version testing, it seems this issue is only with IntelliJ 2022.2 and newer.
2022.1.4 is the last version where the terminal is working correctly with our current code. Luckily this still works with Java17 (but does not require it)

Not sure if there was a change in how the `ShellTerminalWidget` is made in the newer IntelliJ, or if it's just some regression in the IDE.

### Currently without Java17 support, on older IntelliJ versions
When we open a project, a terminal opens up with the project name. This is where the dev start/stop commands will run in. The commands will run in the dedicated project-name terminal without any issues.
![image](https://user-images.githubusercontent.com/689163/202558000-83cbfc70-e16b-4a17-9647-008feb4a5e54.png)

### With IntelliJ 2022.2 and newer which require Java17
With newer versions of IntelliJ, somehow we are not able to open a dedicated terminal for the project. Running dev commands will open a new terminal, and `dev stop` will not be able to find the terminal where `dev start` was run. Present on both MacOS and Windows
![image](https://user-images.githubusercontent.com/689163/202559529-a3d4d155-c0d9-4dd5-9578-326142627f27.png)

**Comment by evie-lau** [comment]
Stack trace of the error:
```
2022-11-17 16:32:07,458 [  48001] SEVERE - #i.o.t.i.a.LibertyGeneralAction - Cannot stop Liberty dev mode, corresponding project terminal does not exist.
java.lang.Throwable: Cannot stop Liberty dev mode, corresponding project terminal does not exist.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at io.openliberty.tools.intellij.actions.LibertyDevStopAction.executeLibertyAction(LibertyDevStopAction.java:42)
	at io.openliberty.tools.intellij.actions.LibertyGeneralAction.actionPerformed(LibertyGeneralAction.java:56)
	at io.openliberty.tools.intellij.LibertyExplorer.executeAction(LibertyExplorer.java:309)
	at io.openliberty.tools.intellij.LibertyExplorer$3.onDoubleClick(LibertyExplorer.java:260)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:422)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
2022-11-17 16:32:07,462 [  48005] SEVERE - #i.o.t.i.a.LibertyGeneralAction - IntelliJ IDEA 2022.2.3  Build #IC-222.4345.14
2022-11-17 16:32:07,462 [  48005] SEVERE - #i.o.t.i.a.LibertyGeneralAction - JDK: 17.0.4.1; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-11-17 16:32:07,462 [  48005] SEVERE - #i.o.t.i.a.LibertyGeneralAction - OS: Mac OS X
2022-11-17 16:32:07,463 [  48006] SEVERE - #i.o.t.i.a.LibertyGeneralAction - Plugin to blame: Liberty Tools version: 0.0.7
```

**Comment by evie-lau** [comment]
From some debugging, it we still create the ShellTerminalWidget properly with the Liberty project name, but the name gets reset immediately. There's a reported issue here: https://youtrack.jetbrains.com/issue/IDEA-297207

**Comment by evie-lau** [comment]
Once #140 gets merged in, we can associate a ShellTerminalWidget for each Liberty project, and grab it from there instead of searching for a matching terminal window name which we currently do in [LibertyProjectUtil](https://github.com/OpenLiberty/liberty-tools-intellij/blob/686bd3664f6ab412d30288c33704532e7b41431d/src/main/java/io/openliberty/tools/intellij/util/LibertyProjectUtil.java#L205-L215)
