### ISSUE TITLE
Hover feature not working for LCLS & LemMinX, MicroProfile properties files

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#147]
The hover feature is not working on any platform for LCLS and LemMinX.

It is suspected that this exception, which occurs over and over, could be the underlying problem:

```
java.lang.IllegalArgumentException: Invalid range specified: (31, 26); 
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:231)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:226)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:222)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:41)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:30)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.completion.LSIncompleteCompletionProposal.getPrefixCompletionStart(LSIncompleteCompletionProposal.java:163)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.completion.LSIncompleteCompletionProposal.<init>(LSIncompleteCompletionProposal.java:84)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.completion.LSCompletionProposal.<init>(LSCompletionProposal.java:26)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.completion.LSContentAssistProcessor.createLookupItem(LSContentAssistProcessor.java:104)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.completion.LSContentAssistProcessor.lambda$toProposals$4(LSContentAssistProcessor.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.completion.LSContentAssistProcessor.toProposals(LSContentAssistProcessor.java:95)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.completion.LSContentAssistProcessor.fillCompletionVariants(LSContentAssistProcessor.java:73)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:76)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:59)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:132)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$11(CompletionProgressIndicator.java:870)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:202)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:114)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:663)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:201)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:43)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:866)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:854)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:352)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:344)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by evie-lau** [comment]
It was mentioned that hover features might have worked before the switch to java17, so I've been investigating if there's any possible changes that might have broken it.
One of the changes was removing the `<project-components>` connecting to the `ConnectDocumentToLanguageServerSetupParticipant` class in `lsp.xml` which is used in `plugin.xml`. This removal was necessary for using newer versions of IntelliJ, and they have a [page](https://plugins.jetbrains.com/docs/intellij/plugin-components.html) talking about it. 
I'm not sure what exactly this was used for, but it seems it may no longer be used, and not sure if it may be related.

**Comment by evie-lau** [comment]
Seems hover may be implemented via a custom implementation referenced in this line:
https://github.com/OpenLiberty/liberty-tools-intellij/blob/2908d53a16704abbb812a4afb6095e9e3907d58e/src/main/resources/META-INF/plugin.xml#L70

Probably related to https://github.com/OpenLiberty/liberty-tools-intellij/issues/192#issuecomment-1339732349 where our <fileType> assignment seems to mess with or override these implementations.

**Comment by evie-lau** [comment]
In lsp.xml, @kathrynkodama and I found that...
With a combination of using LSPTextHover to run on `Properties` files (instead of our custom `MicroProfileConfigProperties`)
```
<lang.documentationProvider id="LSPTextHoverProperties" language="Properties"
                    implementationClass="io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.hover.LSPTextHover"
                    order="first"/>
```

and mapping `Properties` to the lsp4mp language server with:
```
<languageMapping language="Properties" serverId="lsp4mp"/>
```

We were able to get hover working for LSP4MP. A similar configuration worked for bootstrap.properties, but in both cases, we weren't able to utilize a custom `<fileType>` definition. Will be looking into this more.

**Comment by kathrynkodama** [comment]
See https://github.com/OpenLiberty/liberty-tools-intellij/pull/217#issue-1485386915

**Comment by kathrynkodama** [comment]
Hover contributed by each language server (LS):
- [ ] server.xml elements and features, LemMinX + Liberty LemMinX ext: #243 
- [ ] server.env files, Liberty Config LS
- [ ] bootstrap.properties files, Liberty Config LS
- [ ] microprofile-config.properties files, Eclipse LSP4MP
- [ ] Java files, Eclipse LSP4MP. Currently appears but does not populate with values from microprofile-config.properties files: https://github.com/eclipse/lsp4mp/blob/master/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/config/java/MicroProfileConfigHoverParticipant.java  

The properties support from Liberty Config LS and Eclipse LSP4MP are currently conflicting, as detailed in https://github.com/OpenLiberty/liberty-tools-intellij/issues/147#issuecomment-1340406908. Also related to why the values are not populated in the corresponding Java files hover.

Note Eclipse LSP4Jakarta does not currently contribute any hover.
