### ISSUE TITLE
Exception: Cannot invoke "com.intellij.util.messages.MessageBusConnection.disconnect()" 

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#184]
Another red box in the lower right of the IDE. Caused when you switch from one project to another. 

When there is any exception starting the language server it will call `stop()` and this exception will most likely appear:
```
2022-12-01 10:52:34,273 [ 660399]   WARN - i.o.t.i.l.l.LanguageServiceAccessor - Cannot invoke "com.intellij.util.messages.MessageBusConnection.disconnect()" because "this.messageBusConnection" is null
java.lang.NullPointerException: Cannot invoke "com.intellij.util.messages.MessageBusConnection.disconnect()" because "this.messageBusConnection" is null
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageServerWrapper.stop(LanguageServerWrapper.java:431)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageServerWrapper.start(LanguageServerWrapper.java:347)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageServerWrapper.getInitializedServer(LanguageServerWrapper.java:659)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageServiceAccessor.lambda$getLanguageServers$15(LanguageServiceAccessor.java:577)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageServiceAccessor.getLanguageServers(LanguageServiceAccessor.java:590)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.operations.codelens.LSPInlayProvider$2.collect(LSPInlayProvider.java:131)
	at com.intellij.codeInsight.hints.CollectorWithSettings.collectHints(InlayHintsUtils.kt:91)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:47)
	at com.intellij.codeInsight.hints.InlayHintsPass$doCollectInformation$1.process(InlayHintsPass.kt:27)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:86)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by turkeylurkey** [comment]
Most variables are checked for null in stop() but this is not one of them.
