### ISSUE TITLE
"Run Liberty action" action is broken

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#190]
With the enhancements/fixes for #79 and #127 the "Liberty: Run Liberty action" action is broken.

From the shift+shift menu this action does nothing currently.
<img width="846" alt="image" src="https://user-images.githubusercontent.com/26146482/205681613-015bb4b8-9f71-442f-80ca-6fb0ec14c6f5.png">
We should modify so that when selected users are prompted to:
1. Select the Liberty project
2. Select the Liberty action they would like to run

It is also broken when selecting from the Liberty tool window likely due to the changes in #140 
<img width="502" alt="image" src="https://user-images.githubusercontent.com/26146482/205681769-ed7cd603-5d68-40de-be22-bc14e5771a04.png">
```
java.lang.NullPointerException: Cannot invoke "io.openliberty.tools.intellij.LibertyModule.getBuildFile()" because "this.libertyModule" is null
	at io.openliberty.tools.intellij.actions.LibertyDevCustomStartAction.lambda$executeLibertyAction$0(LibertyDevCustomStartAction.java:55)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.openliberty.tools.intellij.actions.LibertyDevCustomStartAction.executeLibertyAction(LibertyDevCustomStartAction.java:46)
	at io.openliberty.tools.intellij.actions.LibertyGeneralAction.actionPerformed(LibertyGeneralAction.java:120)
	at io.openliberty.tools.intellij.actions.RunLibertyDevTask.actionPerformed(RunLibertyDevTask.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:190)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:166)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:166)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
```

**Comment by kathrynkodama** [comment]
Noting that selecting the action from the Liberty tool window will be fixed by https://github.com/OpenLiberty/liberty-tools-intellij/pull/183

**Comment by kathrynkodama** [comment]
With #183, the behaviour is slightly improved when running from the Liberty tool window. The NPE will still appear on the "first" run of Start if using the "Liberty run action" action. However, if you run "Start" through a double-click or through shift-shift, subsequent runs of "Liberty run action" will work.
