### ISSUE TITLE
NPE when trying to start on a Gradle project

### ISSUE THREAD

**Issue by kathrynkodama** [OpenLiberty/liberty-tools-intellij#197]
On Linux, using a gradle app generated by the open liberty starter
```
java.lang.NullPointerException: Cannot invoke "org.jetbrains.plugins.gradle.settings.GradleProjectSettings.getDistributionType()" because "gradleProjectSettings" is null
	at io.openliberty.tools.intellij.util.LibertyGradleUtil.getGradleSettingsCmd(LibertyGradleUtil.java:164)
	at io.openliberty.tools.intellij.actions.LibertyDevStartAction.executeLibertyAction(LibertyDevStartAction.java:36)
	at io.openliberty.tools.intellij.actions.LibertyGeneralAction.actionPerformed(LibertyGeneralAction.java:120)
	at io.openliberty.tools.intellij.LibertyExplorer.executeAction(LibertyExplorer.java:343)
	at io.openliberty.tools.intellij.LibertyExplorer$2.onDoubleClick(LibertyExplorer.java:258)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6648)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3392)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:422)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

We should fail nicer in this scenario

**Comment by dshimo** [comment]
Error popped out when clicking 'Start' twice on a Gradle project

**Comment by mrglavas** [comment]
I immediately hit this issue on Windows when trying to start dev mode on an Open Liberty starter project for Gradle.

**Comment by fabio-franco** [comment]
This issue was solved on https://github.com/OpenLiberty/liberty-tools-intellij/pull/208

**Comment by TrevCraw** [comment]
@kathrynkodama @turkeylurkey do either of you think that we can or should do more in this scenario beyond a null check for the `gradleProjectSettings`? Does it make sense to use or set a default in this case?

**Comment by kathrynkodama** [comment]
@TrevCraw I could see a case made for if `gradleProjectSettings` is null, deliver a warning to users and try the command with just `gradle libertyDev`

**Comment by turkeylurkey** [comment]
My response is similar in that if the user set up JAVA_HOME and GRADLE_HOME `gradle libertyDev` would work for the command line and it should still work in IntelliJ. Presumably the environment is preserved. We need to check.

**Comment by TrevCraw** [comment]
@dshimo, @kathrynkodama and myself are not able to reproduce this issue in environments on Linux, Mac, and Windows respectively.

@mrglavas can still consistently reproduce this issue in his Windows environment. Clearing cache and using a fresh project made no difference. Updating the Gradle settings in IntelliJ also made no difference, so we should probably change our user facing error message for this scenario.

The problem is we still don't know the root cause or what the fix is, so there is no clear direction we can give the user. In Michael's environment, the [Gradle IntelliJ Plugin](https://github.com/JetBrains/gradle-intellij-plugin) works as expected, so Gradle tasks can be run from the IDE, including the `libertyDev` task. Since Liberty Tools is attempting to use the same Gradle settings as the [Gradle IntelliJ Plugin](https://github.com/JetBrains/gradle-intellij-plugin), it seems we might be doing something different.

For next steps, it's probably worth looking further into the [Gradle IntelliJ Plugin](https://github.com/JetBrains/gradle-intellij-plugin) to see how it handles the Gradle settings.

Since this issue is not easily reproduced in multiple environments, I'm going to label it as "nice-to-fix". If we start to see this issue pop up more, we can reevaluate the severity.
