### ISSUE TITLE
Windows: InvalidPathException thrown when running Start... on a Maven project.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#205]
I'm seeing the following exception thrown when I try to run `Start...` on a Maven project with a build of the tools from today.

```
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file://C:/demo-apps/maven-app/pom.xml
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at io.openliberty.tools.intellij.actions.LibertyDevCustomStartAction.lambda$executeLibertyAction$0(LibertyDevCustomStartAction.java:46)
	at com.intellij.util.SmartList.forEach(SmartList.java:344)
	at io.openliberty.tools.intellij.actions.LibertyDevCustomStartAction.executeLibertyAction(LibertyDevCustomStartAction.java:43)
	at io.openliberty.tools.intellij.actions.LibertyGeneralAction.actionPerformed(LibertyGeneralAction.java:120)
	at io.openliberty.tools.intellij.LibertyExplorer.executeAction(LibertyExplorer.java:343)
	at io.openliberty.tools.intellij.LibertyExplorer$2.onDoubleClick(LibertyExplorer.java:258)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
        ...
```

**Comment by kathrynkodama** [comment]
I've seen this happen if there are past run configs (from older versions of the plugin) that weren't deleted. 

@mrglavas can you make sure there are not any existing Liberty run configs, delete with the minus button (see screenshot), then try to reproduce?
![image](https://user-images.githubusercontent.com/26146482/206266894-1bf72a2f-49aa-4f1a-ae56-5b21a27304ce.png)

**Comment by mrglavas** [comment]
@kathrynkodama I cannot reproduce it after deleting the run config. I'll close.
