### ISSUE TITLE
Unable automatically to attach the debugger to JVM

### ISSUE THREAD

**Issue by mezarin** [OpenLiberty/liberty-tools-intellij#348]
Processing a Liberty configuration in debug mode (Run->debug...) on a slow system results in an error. The error is reported through a message on the IDE and the idea.log.

Associated stack trace:

```
2023-04-15 17:59:02,147 [ 459526]   WARN - #io.openliberty.tools.intellij.util.DebugModeHandler - An error was detected while attaching the debugger to the JVM.
java.lang.Exception: Unable to automatically attach the debugger to JVM on host: localhost and port: 36073. If the debug connection timed out but the server did start successfully, you can still manually create a Remote Java Application debug configuration with the mentioned port and attach to the server.
	at io.openliberty.tools.intellij.util.DebugModeHandler.waitForSocketActivation(DebugModeHandler.java:210)
	at io.openliberty.tools.intellij.util.DebugModeHandler.createAndRunDebugConfiguration(DebugModeHandler.java:133)
	at io.openliberty.tools.intellij.util.DebugModeHandler$1.run(DebugModeHandler.java:118)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:425)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:476)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:190)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:666)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:622)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:590)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:177)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

It looks like a wait is missing here:
https://github.com/OpenLiberty/liberty-tools-intellij/blob/main/src/main/java/io/openliberty/tools/intellij/util/DebugModeHandler.java#L178

**Comment by turkeylurkey** [comment]
Weird algorithm that consumes iterations of the polling loop quickly when dev mode has not started yet and server.env has not been created but then consumes iterations very slowly (1/sec) after the file is created. So it is not possible to say how long the IDE waits for the liberty runtime to start because it is non-deterministic.
