### ISSUE TITLE
UI Tests: Unable to find project tree view during setup phase.

### ISSUE THREAD

**Issue by mezarin** [OpenLiberty/liberty-tools-intellij#368]
Error:

GradleSingleModLSTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT1M) for condition function (Failed to find 'JTreeFixture' by '//div[@class='ProjectViewTree' and contains(@visible_text, 'singleModGradleMP')]' in 60s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getProjectViewJTree(ProjectFrameFixture.java:168)
        at io.openliberty.tools.intellij.it.SingleModLibertyLSTestCommon.prepareEnv(SingleModLibertyLSTestCommon.java:300)
        at io.openliberty.tools.intellij.it.GradleSingleModLSTest.setup(GradleSingleModLSTest.java:40)

**Comment by TrevCraw** [comment]
May have been resolved by: https://github.com/OpenLiberty/liberty-tools-intellij/pull/384. Will need to see how test runs go over the next couple weeks.
