### ISSUE TITLE
UI Tests: component must be showing on the screen to determine its location

### ISSUE THREAD

**Issue by mezarin** [OpenLiberty/liberty-tools-intellij#375]
GradleSingleModMPProjectTest > testRunTestsActionUsingDropDownMenu() FAILED
    com.intellij.remoterobot.client.IdeaSideException
        at com.intellij.remoterobot.client.IdeRobotClient.processRetrieveComponentDataResponse(IdeRobotClient.kt:127)
        at com.intellij.remoterobot.client.IdeRobotClient.retrieveComponentData(IdeRobotClient.kt:83)
        at com.intellij.remoterobot.fixtures.Fixture.retrieveData(Fixture.kt:136)
        at com.intellij.remoterobot.fixtures.Fixture.extractData(Fixture.kt:140)
        at com.intellij.remoterobot.fixtures.dataExtractor.ExtractedData.reloadData(ExtractedData.kt:39)
        at com.intellij.remoterobot.fixtures.dataExtractor.ExtractedData.getMany(ExtractedData.kt:36)
        at com.intellij.remoterobot.fixtures.Fixture.findAllText(Fixture.kt:62)
        at com.intellij.remoterobot.fixtures.Fixture.findAllText(Fixture.kt:53)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.runLibertyActionFromLTWDropDownMenu(UIBotTestUtils.java:233)
        at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.testRunTestsActionUsingDropDownMenu(SingleModMPProjectTestCommon.java:160)
        at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base@17.0.6/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base@17.0.6/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)     
...
        Caused by:
        java.lang.Throwable: component must be showing on the screen to determine its location

**Comment by TrevCraw** [comment]
May have been resolved by https://github.com/OpenLiberty/liberty-tools-intellij/pull/384. Will need to see how test runs go over the next couple weeks.

**Comment by vaisakhkannan** [comment]
This issue couldn't be found in the recent Cron Job builds.

**Comment by vaisakhkannan** [comment]
Closing this issue since its not getting now.
