### ISSUE TITLE
Exception when opening microprofile-config.properties file

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#413]
The exception below occurs every time the microprofile-config.properties file is opened.

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[JobScheduler FJ pool 2/11,4,main] 370373727 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 735408048
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:205)
	at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.isInTestSourceContent(ModuleFileIndexImpl.java:113)
	at io.openliberty.tools.intellij.lsp4mp4ij.psi.internal.core.ls.PsiUtilsLSImpl.getClasspathKind(PsiUtilsLSImpl.java:191)
	at io.openliberty.tools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:86)
	at io.openliberty.tools.intellij.lsp4mp4ij.psi.core.PropertiesManager.getMicroProfileProjectInfo(PropertiesManager.java:78)
	at io.openliberty.tools.intellij.lsp4mp.lsp.MicroProfileLanguageClient.lambda$getProjectInfo$2(MicroProfileLanguageClient.java:107)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageClientImpl.lambda$runAsBackground$4(LanguageClientImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageClientImpl.lambda$runAsBackground$5(LanguageClientImpl.java:112)
	at io.openliberty.tools.intellij.lsp4mp.lsp4ij.LanguageClientImpl.lambda$runAsBackground$6(LanguageClientImpl.java:122)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by anusreelakshmi934** [comment]
Tested using Latest Lsp4ij (0.0.2) but was not able to reproduce this issue. Did not came across exception when microprofile-config.properties file is opened.

**Comment by angelozerr** [comment]
LSP4IJ open a non blocking read action when an LanguageClientImpl.lambda#runAsBackground is consumed, so it is normal now that this error no longer exists.

**Comment by TrevCraw** [comment]
Verified this is no longer happening in my environment using `lsp4ij-market-0.0.2-integration` branch.
