### ISSUE TITLE
UI tests: Test times out waiting for server to stop

### ISSUE THREAD

**Issue by mezarin** [OpenLiberty/liberty-tools-intellij#428]
ERROR: 2023-06-01T01:12:22.354451573: testStartWithParamsActionUsingDropDownMenu:validateLibertyServerStopped: Exit. Timed out waiting for message CWWKE0036I in log:/home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/gradle/singleModGradleMP/build/wlp/usr/servers/defaultServer/logs/messages.log
    INFO: 2023-06-01T01:12:22.472522793: GradleSingleModMPProjectTest.testStartWithParamsActionUsingDropDownMenu(). Exit

GradleSingleModMPProjectTest > testStartWithParamsActionUsingDropDownMenu() FAILED
    org.opentest4j.AssertionFailedError: testStartWithParamsActionUsingDropDownMenu:validateLibertyServerStopped: Exit. Timed out waiting for message CWWKE0036I in log:/home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/gradle/singleModGradleMP/build/wlp/usr/servers/defaultServer/logs/messages.log
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
        at org.junit.jupiter.api.Assertions.fail(Assertions.java:135)
        at io.openliberty.tools.intellij.it.TestUtils.validateLibertyServerStopped(TestUtils.java:98)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.runStopAction(UIBotTestUtils.java:1763)
        at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.testStartWithParamsActionUsingDropDownMenu(SingleModMPProjectTestCommon.java:129)

**Comment by anusreelakshmi934** [comment]
This Issue was Investigated and fixed in this [PR](https://github.com/OpenLiberty/liberty-tools-intellij/pull/1049).  Hence closing this ticket.
