### ISSUE TITLE
NullPointerException trying to run the Start action in the Liberty dashboard

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#566]
Unzip the project supplied and load it in IntelliJ. Two entries should appear in the Liberty tools dashboard, app-name-two and app-name-one. Expand app-name-two and double click on Start. The following exception appears in the IntelliJ log and a red question mark will appear in the lower right of the IDE.
```
java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.project.Project.getProjectFilePath()" because the return value of "org.jetbrains.idea.maven.server.MavenServerConnector.getProject()" is null
        at io.openliberty.tools.intellij.util.LibertyMavenUtil.getMavenJdkPath(LibertyMavenUtil.java:321)
        at io.openliberty.tools.intellij.util.LibertyMavenUtil.getCustomMavenPath(LibertyMavenUtil.java:261)
        at io.openliberty.tools.intellij.util.LibertyMavenUtil.getMavenSettingsCmd(LibertyMavenUtil.java:210)
        at io.openliberty.tools.intellij.actions.LibertyDevStartAction.executeLibertyAction(LibertyDevStartAction.java:46)
        at io.openliberty.tools.intellij.actions.LibertyGeneralAction.actionPerformed(LibertyGeneralAction.java:110)
        at io.openliberty.tools.intellij.LibertyExplorer.executeAction(LibertyExplorer.java:347)
        at io.openliberty.tools.intellij.LibertyExplorer$2.onDoubleClick(LibertyExplorer.java:274)
        at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
        at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:58)
        at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
        at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:437)
        at java.desktop/java.awt.Component.processEvent(Component.java:6422)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
```
[two-sep-modules.zip](https://github.com/OpenLiberty/liberty-tools-intellij/files/13281542/two-sep-modules.zip)

**Comment by turkeylurkey** [comment]
Attempted with IntelliJ IDEA 2023.2.3 (Community Edition)
Build #IC-232.10072.27, built on October 11, 2023
Runtime version: 17.0.8.1+7-b1000.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
    open-liberty.intellij (23.0.12-SNAPSHOT)

Kotlin: 232-1.9.0-IJ10072.27
Using Mac OS 14.1 (23B74)
