### ISSUE TITLE
Unable to use the plugin (Start dev mode doesn't work) ... 

### ISSUE THREAD

**Issue by talasilar** [OpenLiberty/liberty-tools-intellij#60]
IntelliJ IDEA 2021.3.1 (Ultimate Edition)
Build #IU-213.6461.79, built on December 28, 2021

2022-01-19 09:01:08,842 [  10078]   INFO - tools.intellij.LibertyExplorer - Liberty Maven Project: XmlFile:pom.xml 
2022-01-19 09:01:08,858 [  10094]   WARN - nSystem.impl.ActionToolbarImpl - Please do not use ActionPlaces.UNKNOWN or the empty place. Any string unique enough to deduce the toolbar location will do. 
java.lang.Throwable: toolbar creation trace
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.<init>(ActionToolbarImpl.java:115)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:425)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.createActionToolbar(ActionManagerImpl.java:420)
	at io.openliberty.tools.intellij.LibertyExplorer.buildActionToolbar(LibertyExplorer.java:65)
	at io.openliberty.tools.intellij.LibertyExplorer.<init>(LibertyExplorer.java:56)
	at io.openliberty.tools.intellij.LibertyDevToolWindowFactory.createToolWindowContent(LibertyDevToolWindowFactory.java:15)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:542)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:521)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1033)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:979)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:968)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doRegisterToolWindow(ToolWindowManagerImpl.kt:1110)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.initToolWindows(ToolWindowManagerImpl.kt:532)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.access$initToolWindows(ToolWindowManagerImpl.kt:86)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$beforeProjectOpenedTask$1.run(ToolWindowManagerImpl.kt:448)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)

**Comment by kathrynkodama** [comment]
Thanks for opening @talasilar, looking into this.

**Comment by talasilar** [comment]
Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by talasilar** [comment]
thank for looking into this.
is there any work around for this ?

**Comment by kathrynkodama** [comment]
@talasilar Since I am unable to reproduce the bug yet, unfortunately the workaround for now would be to run the dev mode commands in the terminal manually. 

If using Maven:
- Navigate to your pom.xml and ensure you have the liberty-maven-plugin configured.
- From the directory containing your pom.xml, run `mvn liberty:dev` to start dev mode.

If using Gradle:
- Navigate to your build.gradle and ensure you have the liberty-gradle-plugin configured. 
- From the directory containing your build.gradle, run `gradle libertyDev` to start dev mode.

See https://openliberty.io/docs/21.0.0.12/development-mode.html for more information on dev mode.

**Comment by TrevCraw** [comment]
Unable to reproduce - please re-open and provide more information if this issue is seen again.
