### ISSUE TITLE
Intermittent test automation initialization failures on MacOS

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#646]
The following errors have been occurring intermittently, but fairly often over the past few weeks:
```
GradleSingleModMPLSTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10M) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'sampleGradleMPLSApp')]' in 600s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getTree(ProjectFrameFixture.java:215)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.validateImportedProjectShowsInLTW(UIBotTestUtils.java:378)
        at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.prepareEnv(SingleModMPLSTestCommon.java:319)
        at io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.setup(GradleSingleModMPLSTest.java:45)

GradleSingleModMPProjectTest STANDARD_OUT
    INFO: 2024-02-03T00:52:27.815078: prepareEnv. Entry. ProjectPath: /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/gradle. ProjectName: singleModGradleMP

GradleSingleModMPProjectTest > initializationError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2M) for condition function (Failed to find 'Welcome Frame' by 'FlatWelcomeFrame type' in 120s) 
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
        at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
        at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
        at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
        at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:34)
        at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
        at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.prepareEnv(SingleModMPProjectTestCommon.java:906)
        at io.openliberty.tools.intellij.it.GradleSingleModMPProjectTest.setup(GradleSingleModMPProjectTest.java:78)
```
Below is a list of jobs that have run into this issue:

https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7805263938/job/21289066845
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7762957374/job/21174304771
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7759122950/job/21162481094
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7758920824/job/21161788244
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7758850340/job/21161548463
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7752853985/job/21143064368
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7751536926/job/21140904867
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7472330586/job/20334283842
https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/7223872376/job/19683881434

**Comment by turkeylurkey** [comment]
Still happening, here is another sample:
```
GradleSingleModJakartaLSTest > testJakartaQuickFixInJavaPart() FAILED
    java.net.SocketTimeoutException: Read timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
        at okio.InputStreamSource.read(JvmOkio.kt:94)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
        at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
        at com.intellij.remoterobot.client.IdeRobotClient.execute(IdeRobotClient.kt:59)
        at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:35)
        at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
        at com.intellij.remoterobot.JavaScriptApi$DefaultImpls.runJs(JavaScriptApi.kt:25)
        at com.intellij.remoterobot.RemoteRobot.runJs(RemoteRobot.kt:32)
        at com.intellij.remoterobot.utils.Keyboard$enterText$1.invoke(KeyboardUtils.kt:49)
        at com.intellij.remoterobot.utils.Keyboard$enterText$1.invoke(KeyboardUtils.kt:48)
        at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
        at com.intellij.remoterobot.utils.Keyboard.enterText(KeyboardUtils.kt:48)
        at com.intellij.remoterobot.utils.Keyboard.enterText$default(KeyboardUtils.kt:48)
        at com.intellij.remoterobot.utils.Keyboard.enterText(KeyboardUtils.kt)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.selectAndModifyTextInJavaPart(UIBotTestUtils.java:1294)
        at io.openliberty.tools.intellij.it.SingleModJakartaLSTestCommon.testJakartaQuickFixInJavaPart(SingleModJakartaLSTestCommon.java:149)
       ```
       In https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/8436692171/job/23104688837
