### ISSUE TITLE
Jakarta EE completion throws an IllegalArgumentException when typing within a method.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#681]
Within IntelliJ, I'm seeing this exception appearing frequently while typing in a method. It's trying to compute the cursor context but failing when it attempts to convert `JavaCursorContextKind` enum values from LSP4MP to the LSP4Jakarta equivalent. This is specifically an issue with conversion of `JavaCursorContextKind.NONE` which has a value of 2000. The `forValue()` method assumes that none of the values are greater than the number of enum values and throws the exception when 2000 is passed in. In my opinion this is a bug in both LSP4MP and LSP4Jakarta but can be easily worked around.

```
java.lang.IllegalArgumentException: Illegal enum value: 2000
	at org.eclipse.lsp4jakarta.commons.JavaCursorContextKind.forValue(JavaCursorContextKind.java:230)
	at io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.PropertiesManagerForJakarta.adapt(PropertiesManagerForJakarta.java:126)
	at io.openliberty.tools.intellij.lsp4jakarta.lsp4ij.PropertiesManagerForJakarta.javaCursorContext(PropertiesManagerForJakarta.java:86)
	at io.openliberty.tools.intellij.lsp4jakarta.lsp.JakartaLanguageClient.lambda$getJavaCompletion$3(JakartaLanguageClient.java:90)
	at org.microshed.lsp4ij.internal.PromiseToCompletableFuture.lambda$nonBlockingReadActionPromise$2(PromiseToCompletableFuture.java:137)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:840)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:872)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	... 27 more
```

Current implementation of `JavaCursorContextKind.forValue()` in LSP4Jakarta:

```
    public static JavaCursorContextKind forValue(int value) {
        JavaCursorContextKind[] allValues = JavaCursorContextKind.values();
        if (value < 1 || value > allValues.length)
            throw new IllegalArgumentException("Illegal enum value: " + value);
        return allValues[value - 1];
    }
```

**Comment by mrglavas** [comment]
`DocumentFormat` is another enum which exists in both LSP4MP and LSP4Jakarta. `PropertiesManagerForJakarta` also converts values from these two types using its `forValue()` method. I verified that this enum does not have the same problem that's being investigated here for `JavaCursorContextKind`.
