### ISSUE TITLE
IntelliJ IDEA 2024.1 support: Resolve warning about deprecation of ActionUpdateThread.OLD_EDT.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#720]
After upgrading to IntelliJ IDEA 2024.1 the following error is reported with guidance on how to resolve it:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.openliberty.tools.intellij.actions.RunLibertyDevTask' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: open-liberty.intellij]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
	...
```

This will require a change to the Liberty dev mode actions.

**Comment by mrglavas** [comment]
Resolved by https://github.com/OpenLiberty/liberty-tools-intellij/pull/734.
