### ISSUE TITLE
LSP4iJ 2024/04/01 integration: Find usages on a Java file can generate many IDE internal errors.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#735]
I reported this in the Red Hat LSP4iJ project: https://github.com/redhat-developer/lsp4ij/issues/273. Opening an issue here for tracking the same resolution in the MicroShed version of LSP4iJ. While correct results are being displayed in the IDE, a user who triggers this will also get many internal IDE errors that were never produced before.

Sample stack trace:
```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 14,4,main] 622491191 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 190305548
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:180)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:131)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:908)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStubTree(ClsFileImpl.java:471)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getStub(ClsFileImpl.java:451)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getClasses(ClsFileImpl.java:136)
	at com.intellij.psi.impl.compiled.ClsFileImpl.getMirror(ClsFileImpl.java:335)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getMirror(ClsElementImpl.java:132)
	at com.intellij.psi.impl.compiled.ClsElementImpl.getTextRange(ClsElementImpl.java:139)
	at org.microshed.lsp4ij.usages.LSPUsageSearcher.getPosition(LSPUsageSearcher.java:90)
	at org.microshed.lsp4ij.usages.LSPUsageSearcher.processElementUsages(LSPUsageSearcher.java:66)
        ...
```

**Comment by mrglavas** [comment]
Resolved by https://github.com/MicroShed/lsp4ij/pull/19.
