### ISSUE TITLE
Resolve build failures in main branch

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#764]
Builds started failing as of these build runs: https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/9061057971

failures:
 - java.lang.RuntimeException: Hover on text: 'getProperties' did not trigger a pop-up window to open 
    at io.openliberty.tools.intellij.it.UIBotTestUtils.hoverForQuickFixInAppFile(UIBotTestUtils.java:889)
        at io.openliberty.tools.intellij.it.SingleModJakartaLSTestCommon.testJakartaQuickFixInJavaPart (SingleModJakartaLSTestCommon.java:156)
 (covered in #748)
 - MavenSingleModMPProjectTest > testRunTestsActionUsingSearch() FAILED
    org.opentest4j.AssertionFailedError: testRunTestsActionUsingSearch:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available. 
at io.openliberty.tools.intellij.it.TestUtils.validateProjectStarted(TestUtils.java:166)
        at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.testRunTestsActionUsingSearch (SingleModMPProjectTestCommon.java:444)
 #769
 - MavenSingleModNLTRestProjectTest.testManualProjectAddRemoveActionUsingSearch(). Exit
MavenSingleModNLTRestProjectTest > testManualProjectAddRemoveActionUsingSearch() FAILED
    java.lang.RuntimeException: Failed to run the Liberty: Add project to the tool window action using the search everywhere option 
MavenSingleModNLTRestProjectTest > testManualProjectAddRemoveActionUsingSearch() FAILED
    java.lang.RuntimeException: Failed to run the Liberty: Add project to the tool window action using the search everywhere option
        at io.openliberty.tools.intellij.it.UIBotTestUtils.runActionFromSearchEverywherePanel(UIBotTestUtils.java:1642)
        at io.openliberty.tools.intellij.it.SingleModNLTRestProjectTestCommon.testManualProjectAddRemoveActionUsingSearch (SingleModNLTRestProjectTestCommon.java:84)
   #768
 - MavenSingleModNLTRestProjectTest > testsRefreshProjectWithLTBuildCfgOnlyWithBldScriptBlock() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'singleModMavenRESTNoLTXmlCfg')]' in 10s) 
MavenSingleModNLTRestProjectTest > testsRefreshProjectWithLTBuildCfgOnlyWithBldScriptBlock() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'singleModMavenRESTNoLTXmlCfg')]' in 10s) 
        at com.intellij.remoterobot....
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getTree(ProjectFrameFixture.java:215)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.findProjectInLibertyToolWindow(UIBotTestUtils.java:336)
        at io.openliberty.tools.intellij.it.SingleModNLTRestProjectTestCommon.testsRefreshProjectWithLTBuildCfgOnly (SingleModNLTRestProjectTestCommon.java:194)
        at io.openliberty.tools.intellij.it.SingleModNLTRestProjectTestCommon.testsRefreshProjectWithLTBuildCfgOnlyWithBldScriptBlock (SingleModNLTRestProjectTestCommon.java:161)
 #768
 - MavenSingleModNLTRestProjectTest > testsRefreshProjectWithServerXmlOnly() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'singleModMavenRESTNoLTXmlCfg')]' in 10s) 
MavenSingleModNLTRestProjectTest > testsRefreshProjectWithServerXmlOnly() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'singleModMavenRESTNoLTXmlCfg')]' in 10s) 
        at com.intellij.remoterobot....
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getTree(ProjectFrameFixture.java:215)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.findProjectInLibertyToolWindow(UIBotTestUtils.java:336)
        at io.openliberty.tools.intellij.it.SingleModNLTRestProjectTestCommon.testsRefreshProjectWithServerXmlOnly (SingleModNLTRestProjectTestCommon.java:136)
#768
 - MavenSingleModNLTRestProjectTest > executionError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Menu items containing the Close Project text were not found) 
MavenSingleModNLTRestProjectTest > testsRefreshProjectWithServerXmlOnly() FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'singleModMavenRESTNoLTXmlCfg')]' in 10s) 
MavenSingleModNLTRestProjectTest > executionError FAILED
    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Menu items containing the Close Project text were not found) 
        at com.intellij.remoterobot....
        at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getActionMenuItem(ProjectFrameFixture.java:79)
        at io.openliberty.tools.intellij.it.UIBotTestUtils.closeProjectFrame(UIBotTestUtils.java:217)
        at io.openliberty.tools.intellij.it.SingleModNLTRestProjectTestCommon.cleanup (SingleModNLTRestProjectTestCommon.java:69)
 `Same as previous?`
 
`105 tests completed, 6 failed, 8 skipped`

**Comment by turkeylurkey** [comment]
`MavenSingleModMPProjectTest > testRunTestsActionUsingSearch() FAILED` caused by previous test failure

**Comment by turkeylurkey** [comment]
`MavenSingleModNLTRestProjectTest.testManualProjectAddRemoveActionUsingSearch()` passes locally. Invokes IntelliJ new project dialog on GHA.

**Comment by turkeylurkey** [comment]
Reran the build of this pull request and it passed
<img width="759" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/8030a808-bfac-43fb-941a-b5a9eeb1c547">
<img width="209" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/8da8e8fe-0e34-4877-94a1-f4fe71fbe358">
Reran the previous commit and it failed
<img width="676" alt="image" src="https://github.com/OpenLiberty/liberty-tools-intellij/assets/24705144/794b1fc1-a65e-4321-8480-078725d6c351">

**Comment by turkeylurkey** [comment]
#748 delayed to next milestone.
