### ISSUE TITLE
Investigate time out waiting for test report

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/liberty-tools-intellij#934]
The builds started consistently failing for each platform. We need to investigate what is causing this.

For Linux and Windows, it looks like each of the failures are coming from tests that attempt to run project tests through dev mode and hit this error:
```
java.lang.IllegalStateException: Timed out waiting for test report: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/site/failsafe-report.html file to be created.
        at io.openliberty.tools.intellij.it.TestUtils.validateTestReportExists(TestUtils.java:396)
```

Refer to this workflow run: https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/10590421767

**Comment by turkeylurkey** [comment]
After we click on `Run Tests` the system starts many dozens of Maven downloads but these proceed quickly on Linux and the tests seem to run correctly right after. 
![image](https://github.com/user-attachments/assets/6f2b4f17-1f91-41a8-bb9b-7d55508088cd)
After clicking on `Run Tests` the process waits 100s for the test files to appear. This seems like it should be enough so we should see if the result files are going somewhere else instead of `target/site`. Possibly the file names changed for some reason.

**Comment by turkeylurkey** [comment]
In a linux test the log shows what files are being examined:
```
MavenSingleModMPProjectTest > testRunTestsActionUsingSearch() STANDARD_OUT
    INFO: 2024-08-28T16:22:00.675403834: MavenSingleModMPProjectTest.testRunTestsActionUsingSearch(). Entry
    INFO: 2024-08-28T16:22:00.680408280: deleteFile. Entry. Path: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/site/failsafe-report.html
    INFO: 2024-08-28T16:22:00.680448806: deleteFile. Exit. Deleted: true
    INFO: 2024-08-28T16:22:00.680725534: deleteFile. Entry. Path: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/site/surefire-report.html
    INFO: 2024-08-28T16:22:00.680762032: deleteFile. Exit. Deleted: true
```
The files are deleted or they were not there. The error message is 
```
java.lang.IllegalStateException: Timed out waiting for test report: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/site/failsafe-report.html file to be created.
        at io.openliberty.tools.intellij.it.TestUtils.validateTestReportExists(TestUtils.java:396)
```
and the file name matches what was deleted earlier.

**Comment by turkeylurkey** [comment]
We have been using `target/site` as the directory for Junit test results but in this current run the directories in `target` do not include `site`. 
<img width="295" alt="image" src="https://github.com/user-attachments/assets/bb6d8a5b-3b1f-4157-9b85-f2f5473c492a">
There are some other directories that look like they could hold the test results but why has there been a change?

**Comment by anusreelakshmi934** [comment]
> In a linux test the log shows what files are being examined:
> 
> ```
> MavenSingleModMPProjectTest > testRunTestsActionUsingSearch() STANDARD_OUT
>     INFO: 2024-08-28T16:22:00.675403834: MavenSingleModMPProjectTest.testRunTestsActionUsingSearch(). Entry
>     INFO: 2024-08-28T16:22:00.680408280: deleteFile. Entry. Path: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/site/failsafe-report.html
>     INFO: 2024-08-28T16:22:00.680448806: deleteFile. Exit. Deleted: true
>     INFO: 2024-08-28T16:22:00.680725534: deleteFile. Entry. Path: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/site/surefire-report.html
>     INFO: 2024-08-28T16:22:00.680762032: deleteFile. Exit. Deleted: true
> ```
> 
> The files are deleted or they were not there. The error message is
> 
> ```
> java.lang.IllegalStateException: Timed out waiting for test report: /home/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/site/failsafe-report.html file to be created.
>         at io.openliberty.tools.intellij.it.TestUtils.validateTestReportExists(TestUtils.java:396)
> ```
> 
> and the file name matches what was deleted earlier. The second file (`surefire-report.html`) is not sought and the test case waits 60s after the file check before stopping the server.

At the beginning of the test we first Delete any existing test report files if already present. So it deletes the failsafe-report.html file in target/site. Then the test begins and run tests action occurs. After the run tests. the new failsafe-report.html will be created in the target/site. It seems like the file is not being created again.

**Comment by anusreelakshmi934** [comment]
> We have been using `target/site` as the directory for Junit test results but in this current run the directories in `target` do not include `site`. <img alt="image" width="295" src="https://private-user-images.githubusercontent.com/24705144/362534495-bb6d8a5b-3b1f-4157-9b85-f2f5473c492a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTAzOTksIm5iZiI6MTcyNDkxMDA5OSwicGF0aCI6Ii8yNDcwNTE0NC8zNjI1MzQ0OTUtYmI2ZDhhNWItM2IxZi00MTU3LTliODUtZjJmNTQ3M2M0OTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA1NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NmIxMDQ2ZGFhNDViNTMzOTkxZTJlODQyZjZmMjJkMzViYjVmYzJmYmI3MDdjMzgzZGFkYjVlMDgzNDA5MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-uSqgDmvbKYrqOtotTDugsFnsPnU41SHySe3XlRA30"> There are some other directories that look like they could hold the test results but why has there been a change?

site will only be created after we run the tests.

**Comment by aparnamichael** [comment]
Maven surefire plugin and maven failsafe plugin updated on Aug 27th. We suspect this release is causing problem with html report.

https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-failsafe-plugin
https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-surefire-plugin

**Comment by turkeylurkey** [comment]
This is more of a question than a finding or an answer. Here we start running unit tests and downloading dependencies.
<img width="1241" alt="image" src="https://github.com/user-attachments/assets/474f3942-5d84-4e03-ab0a-edb5a337bc62">
After downloading 12 jars the tests run but none of the downloads are failsafe jar
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/320ce13f-f626-4d7a-a499-0739358d5220">
Why is it downloading surefire but not failsafe?

**Comment by turkeylurkey** [comment]
I tried to specify surefire 3.5.0 in pom.xml in the test case but I could not reproduce the issue. I deleted the .m2/repository locally and forced everything to be downloaded and I did reproduce the issue.

**Comment by TrevCraw** [comment]
We should test the Run Tests and View Test Report actions with our current release (24.0.6) to see if we are broken in production.

**Comment by turkeylurkey** [comment]
Same problem exists with 24.0.6. I used my machine that exhibited the problem using our dev code and I ran the same test using 24.0.6.
<img width="549" alt="image" src="https://github.com/user-attachments/assets/a627066d-77c5-4922-a67e-1723cc9fe2e1">
No html files in `site`.

**Comment by TrevCraw** [comment]
I think we want to try to understand a few things:
1. What is dev mode's connection with the surefire and failsafe plugins?
2. Why is the latest version of these plugins being downloaded? And do we always want to use the latest version?
3. What changes in the latest plugin version of surefire or failsafe is causing Liberty Tools to break?

**Comment by turkeylurkey** [comment]
In dev mode we run this code for unit tests:
```
             runTestMojo("org.apache.maven.plugins", "maven-surefire-plugin", "test", currentProject);
             runTestMojo("org.apache.maven.plugins", "maven-surefire-report-plugin", "report-only", currentProject);
```
which means `mvn org.apache.maven.plugins:maven-surefire-plugin:test` etc. For integration tests:
```
                runTestMojo("org.apache.maven.plugins", "maven-failsafe-plugin", "integration-test", currentProject);
                runTestMojo("org.apache.maven.plugins", "maven-surefire-report-plugin", "failsafe-report-only", currentProject);
                runTestMojo("org.apache.maven.plugins", "maven-failsafe-plugin", "verify", currentProject);
```
We don't specify version numbers so it probably just uses 'RELEASE' to use the latest. 
https://github.com/OpenLiberty/ci.maven/blob/d8c90d8f2d8b30b19c68bab2a5601d91d4f488fb/liberty-maven-plugin/src/main/java/io/openliberty/tools/maven/server/DevMojo.java#L1266

**Comment by turkeylurkey** [comment]
I tried running this command in the terminal to force v3.4 to be downloaded before starting the server and running tests in the Liberty Tool Window. 
```
./mvnw org.apache.maven.plugins:maven-surefire-report-plugin:3.4.0:report-only 
```
I verified that v3.4 was downloaded into the local repository but when I started the server and used `Run Tests` it still downloaded v3.5.0 and LTI did not produce the correct html files.

**Comment by turkeylurkey** [comment]
There are html files:
![image](https://github.com/user-attachments/assets/3212d08e-56e8-4e75-828a-24e62e1de024)

**Comment by aparnamichael** [comment]
@TrevCraw @turkeylurkey 

In our LTI code, we are hard coding this path for the actions "view integration test report" and "view unit test report". The change of directory will also affect the functionality of both these liberty actions.

    // get path to project folder
        final VirtualFile parentFile = buildFile.getParent();
        File failsafeReportFile = Paths.get(parentFile.getPath(), "target", "site", "failsafe-report.html").normalize().toAbsolutePath().toFile();
        
        After clearing the m2 in our local and then if we click on "view integration test report" and "view unit test report", it will throw an error "Test report does not exist", as we have hardcoded the above path in our code but the actual test report file is inside "/target/reports". If we change the hardcoded path to "/target/reports" then existing users who use old plugin version, will get the "Test report does not exist", because their report will still generate inside "site" folder.

**Comment by turkeylurkey** [comment]
In the case it was working there were 4 or 5 different versions of `maven-surefire-report-plugin` in the local repository. Also there were some .pom and .xml files as well. The lowest version number was 3.2.5. I suspect these other files are necessary for dev mode to have the plugins in its internal management data structure. When dev mode finds this plugin locally it does not need to download the latest release. Perhaps we could use this to work around the issue.

**Comment by TrevCraw** [comment]
I am not sure if the fix for this will be specifying one version of the `maven-surefire-report-plugin` for dev mode to use. I don't know if dev mode should be limited to a specific version or continue to pull the latest. I feel like this issue needs wider discussion amongst the guild (cc @cherylking @scottkurz).

From a Liberty Tools perspective, even if dev mode specifies a version to download, a user could install any version of these plugins that they would like. Therefore, I think we need to be able to handle the behaviour pre `3.5.0` and post `3.5.0`. This issue will likely also affect Liberty Tools for Eclipse and Liberty Tools for VS Code. Below are a couple potential solutions. I am open to others.

1. Liberty Tools looks for the version of `maven-surefire-report-plugin` installed and then looks for the test report based on the version.
2. Liberty Tools always looks in both potential test report locations and displays the test report that is found. (I guess in this case we would need to determine a priority location in the unlikely event a test report is in both locations)

**Comment by scottkurz** [comment]
Agree this is really about the change in maven-surefire-report-plugin version than changes in the surefire/failsafe plugin itself.     From liberty:dev, IIUC, we are calling maven-surefire-report-plugin without specifying a version, so we're subjecting ourselves to different behavior depending on what the user happens to have installed.

This does seem to call out for a design discussion.  Should we change dev mode or the Liberty Tools IDE tools?    If we're changing Liberty Tools should we just add one more default location or should we go to the step of actually reading the user's config (which could be set to a whole other location).   I'm not sure I see us going in a whole other step of using an IDE-specific config of our own... but I'm not sure that's out of the question either.

**Comment by TrevCraw** [comment]
Since the next LTI release is coming soon, we are going to move forward with a fix for LTI. We can always make changes if necessary based on the results of the design discussion. For now, we are going to check both test report locations, looking at the new location first.

**Comment by turkeylurkey** [comment]
Idea #1 wont necessarily work because there are typically multiple versions of a plugin in the local repository. 
![image](https://github.com/user-attachments/assets/a52ad533-c918-4580-91f7-00d2d052d6a1)
I didn't even do much to get these 5 versions. Also the test case could hard code a version of a plugin but that may not affect the choice dev mode makes.

**Comment by vaisakhkannan** [comment]
I found this issue in recent cron job build failure

```
MavenSingleModMPSIDProjectTest > testRunTestsActionUsingDropDownMenu() FAILED
    java.lang.IllegalStateException: Timed out waiting for test report: D:\a\liberty-tools-intellij\liberty-tools-intellij\liberty-tools-intellij\src\test\resources\projects\maven sample\singleModMavenMP\target\site\failsafe-report.html or D:\a\liberty-tools-intellij\liberty-tools-intellij\liberty-tools-intellij\src\test\resources\projects\maven sample\singleModMavenMP\target\reports\failsafe.html file to be created.
        at io.openliberty.tools.intellij.it.TestUtils.validateTestReportExists(TestUtils.java:405)
        at io.openliberty.tools.intellij.it.MavenSingleModMPSIDProjectTest.validateTestReportsExist(MavenSingleModMPSIDProjectTest.java:120)
```
Build link : https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13028397931/job/36342045159

I could see this intermittent issues in other Cron Job builds as well.
