### ISSUE TITLE
Mac automated UI test failure: initializationErrors

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#971]
Two test cases fail during initialization so there is no movie in the build output. These movies are used to debug the test failure so we'll need to debug these failures by adding debug logging.

- GradleSingleModMPLSTest > initializationError FAILED
- GradleSingleModMPProjectTest > initializationError FAILED

> GradleSingleModMPLSTest > initializationError FAILED
>     com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10M) for condition function (Failed to find 'ComponentFixture' by '//div[@class='Tree' and @name='LibertyTree' and contains(@visible_text, 'sampleGradleMPLSApp')]' in 600s) 
>         at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
>         at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
>         at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
>         at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
>         at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
>         at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
>         at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
>         at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getTree(ProjectFrameFixture.java:215)
>         at io.openliberty.tools.intellij.it.UIBotTestUtils.validateImportedProjectShowsInLTW(UIBotTestUtils.java:382)
>         at io.openliberty.tools.intellij.it.SingleModMPLSTestCommon.prepareEnv(SingleModMPLSTestCommon.java:317)
>         at io.openliberty.tools.intellij.it.GradleSingleModMPLSTest.setup(GradleSingleModMPLSTest.java:45)

> GradleSingleModMPProjectTest > initializationError FAILED
>     com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2M) for condition function (Failed to find 'Welcome Frame' by 'FlatWelcomeFrame type' in 120s) 
>         at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
>         at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
>         at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
>         at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
>         at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
>         at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
>         at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
>         at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:34)
>         at com.intellij.remoterobot.RemoteRobot.find(RemoteRobot.kt:32)
>         at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.prepareEnv(SingleModMPProjectTestCommon.java:915)
>         at io.openliberty.tools.intellij.it.GradleSingleModMPProjectTest.setup(GradleSingleModMPProjectTest.java:83)

**Comment by turkeylurkey** [comment]
Around 30% of the time this test case fails in the same way.
> GradleSingleModJakartaLSTest > initializationError FAILED
>    com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT1M) for condition function (Failed to find 'JTreeFixture' by '//div[@class='ProjectViewTree' and contains(@visible_text, 'sampleGradleMPLSApp')]' in 60s) 
>         at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor(RepeatUtils.kt:51)
>         at com.intellij.remoterobot.utils.RepeatUtilsKt.waitFor$default(RepeatUtils.kt:37)
>         at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:53)
>         at com.intellij.remoterobot.SearchContext$find$1.invoke(SearchContext.kt:51)
>         at com.intellij.remoterobot.stepsProcessing.StepWorkerKt.step(StepWorker.kt:23)
>         at com.intellij.remoterobot.SearchContext$DefaultImpls.find(SearchContext.kt:51)
>         at com.intellij.remoterobot.fixtures.ContainerFixture.find(ContainerFixture.kt:12)
>         at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getProjectViewJTree(ProjectFrameFixture.java:172)
>         at io.openliberty.tools.intellij.it.SingleModJakartaLSTestCommon.prepareEnv(SingleModJakartaLSTestCommon.java:189)
        at io.openliberty.tools.intellij.it.GradleSingleModJakartaLSTest.setup(GradleSingleModJakartaLSTest.java:43)
