### ISSUE TITLE
Mac automated UI test failure: missing diagnostic in server.env

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#972]
A valid key is added to `server.env` but an invalid value is specified. It seems the diagnostic is not displayed. This is intermittent.
![image](https://github.com/user-attachments/assets/e0031893-b7f7-4dc1-b3ee-345019115666)
Even the project tree agrees.
![image](https://github.com/user-attachments/assets/5ba5c577-19ff-4709-9ae5-015b3690a3f1)

> GradleSingleModLSTest > testDiagnosticInServerEnv() FAILED
>     java.lang.RuntimeException: Hover on text: NONE did not trigger a pop-up window to open
>         at io.openliberty.tools.intellij.it.UIBotTestUtils.hoverInAppServerCfgFile(UIBotTestUtils.java:828)
>         at io.openliberty.tools.intellij.it.SingleModLibertyLSTestCommon.testDiagnosticInServerEnv(SingleModLibertyLSTestCommon.java:339)
> ...

> Caused by:
>         com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT5S) for condition function (Failed to find 'Container' by '//div[@class='HeavyWeightWindow']//div[@class='JEditorPane']' in 5s) 
> ...
> at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getDiagnosticPane(ProjectFrameFixture.java:259)
>             at io.openliberty.tools.intellij.it.UIBotTestUtils.hoverInAppServerCfgFile(UIBotTestUtils.java:810)

**Comment by turkeylurkey** [comment]
Using LCLS 2.2-SNAPSHOT 9 of 10 test runs on Mac did not hit this problem. The one failure was caused by the close/re-open work-around. The Windows test run did fail 1 of 1 try.

**Comment by turkeylurkey** [comment]
The fix for Windows #945 may help on the Mac too.

**Comment by turkeylurkey** [comment]
Dependent on LCLS update #1006

**Comment by turkeylurkey** [comment]
Fixed by https://github.com/OpenLiberty/liberty-tools-intellij/pull/1051
