### ISSUE TITLE
Mac automated UI test failure: completion unavailable in server.env

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#973]
Part of a key is typed in `server.env` and completion is attempted but no alternatives are offered. Intermittent.
![image](https://github.com/user-attachments/assets/0dde8106-b141-45f8-aa5b-de5c188252af)

> GradleSingleModLSTest > testInsertLibertyConfigIntoServerEnv() FAILED
>     java.lang.RuntimeException: Unable to insert entry in config file : server.env using text: WLP_LOGGING_CON
>         at io.openliberty.tools.intellij.it.UIBotTestUtils.insertConfigIntoConfigFile(UIBotTestUtils.java:1136)
>         at io.openliberty.tools.intellij.it.SingleModLibertyLSTestCommon.testInsertLibertyConfigIntoServerEnv(SingleModLibertyLSTestCommon.java:171)
> ...

> Caused by:
>         com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT10S) for condition function (Failed to find 'Container' by '//div[@class='HeavyWeightWindow']//div[@class='LookupList']' in 10s) 
> ...
> at io.openliberty.tools.intellij.it.fixtures.ProjectFrameFixture.getLookupList(ProjectFrameFixture.java:309)
>             at io.openliberty.tools.intellij.it.UIBotTestUtils.insertConfigIntoConfigFile(UIBotTestUtils.java:1088)

**Comment by TrevCraw** [comment]
Need to confirm if this issue has been resolved by https://github.com/OpenLiberty/liberty-tools-intellij/pull/1051.

**Comment by vaisakhkannan** [comment]
This issue no longer occurs in recent Cron Jobs and normal builds. It looks like the above-mentioned PR has also resolved this issue, so we can close it.
