### ISSUE TITLE
Mac automated UI test failure: Timed out while waiting for server to start

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/liberty-tools-intellij#974]
The server is started using Shift-Shift window and the server log is included in the test results. It shows the server is shutdown 10s after it starts up but it does not show the required app is started. 

Intermittent.
`ERROR: 2024-09-11T21:23:07.586129: testRunTestsActionUsingSearch:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.`

> MavenSingleModMPProjectTest > testRunTestsActionUsingSearch() FAILED
>     org.opentest4j.AssertionFailedError: testRunTestsActionUsingSearch:validateProjectStarted: Timed out while waiting for project with resource URI api/resourceand port 9080 to become available.
>         at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
>         at org.junit.jupiter.api.Assertions.fail(Assertions.java:135)
>         at io.openliberty.tools.intellij.it.TestUtils.validateProjectStarted(TestUtils.java:166)
>         at io.openliberty.tools.intellij.it.SingleModMPProjectTestCommon.testRunTestsActionUsingSearch(SingleModMPProjectTestCommon.java:453)

Waiting for "URI api/resourceand port 9080" and app in log below is "CWWKT0016I: Web application available (default_host): http://mac-1726079118840.local:9080/health/"

> Message log for failed test: testRunTestsActionUsingSearch:validateProjectStarted
>     ---------------------------------------------------------------------
>     ********************************************************************************
>     product = Open Liberty 24.0.0.9 (wlp-1.0.93.cl241020240827-1743)
>     wlp.install.dir = /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/
>     java.home = /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/test-tools/liberty-dev-tools/jdk-17.0.6+10/Contents/Home
>     java.version = 17.0.6
>     java.runtime = IBM Semeru Runtime Open Edition (17.0.6+10)
>     os = Mac OS X (14.6.1; x86_64) (en_US)
>     process = 22137@Mac-1726079118840.local
>     Classpath = /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/bin/tools/ws-server.jar:/Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/bin/tools/ws-javaagent.jar
>     Java Library path = /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/test-tools/liberty-dev-tools/jdk-17.0.6+10/Contents/Home/lib/default:/Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/test-tools/liberty-dev-tools/jdk-17.0.6+10/Contents/Home/lib:/usr/lib
>     ********************************************************************************
>     [9/11/24, 21:15:12:953 UTC] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0001I: The server defaultServer has been launched.
>     [9/11/24, 21:15:14:972 UTC] 0000001f com.ibm.ws.config.xml.internal.ServerXMLConfiguration        A CWWKG0093A: Processing configuration drop-ins resource: /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/configDropins/defaults/quick-start-security.xml
>     [9/11/24, 21:15:15:708 UTC] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           I CWWKE0002I: The kernel started after 9.362 seconds
>     [9/11/24, 21:15:15:734 UTC] 00000028 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0007I: Feature update started.
>     [9/11/24, 21:15:17:411 UTC] 0000001e com.ibm.ws.app.manager.internal.monitor.DropinMonitor        A CWWKZ0058I: Monitoring dropins for applications.
>     [9/11/24, 21:15:24:485 UTC] 00000029 com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application singleModMavenMP.
>     [9/11/24, 21:15:24:489 UTC] 00000029 bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0134I: The singleModMavenMP application is using the loose application definition at the /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/apps/singleModMavenMP.war.xml location.
>     [9/11/24, 21:15:24:931 UTC] 0000002d com.ibm.ws.webcontainer.osgi.webapp.WebGroup                 I SRVE0169I: Loading Web Module: health.
>     [9/11/24, 21:15:24:937 UTC] 0000002d com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module health has been bound to default_host.
>     [9/11/24, 21:15:24:940 UTC] 0000002d com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://mac-1726079118840.local:9080/health/
>     [9/11/24, 21:15:25:224 UTC] 0000002a com.ibm.ws.session.WASSessionCore                            I SESN8501I: The session manager did not find a persistent storage location; HttpSession objects will be stored in the local application server's memory.
>     [9/11/24, 21:15:25:347 UTC] 0000002c com.ibm.ws.session.WASSessionCore                            I SESN0176I: A new session context will be created for application key default_host/health
>     [9/11/24, 21:15:25:352 UTC] 0000002c com.ibm.ws.util                                              I SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
>     [9/11/24, 21:15:25:527 UTC] 00000029 org.jboss.weld.Version                                       I WELD-000900: 4.0.3 (Final)
>     [9/11/24, 21:15:25:586 UTC] 0000002c com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckReadinessServlet]: Initialization successful.
>     [9/11/24, 21:15:25:588 UTC] 0000002c com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckServlet]: Initialization successful.
>     [9/11/24, 21:15:25:593 UTC] 0000002c com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckStartupServlet]: Initialization successful.
>     [9/11/24, 21:15:25:594 UTC] 0000002c com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckLivenessServlet]: Initialization successful.
>     [9/11/24, 21:15:25:893 UTC] 0000002a com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator          I SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/logs/state/plugin-cfg.xml.
>     [9/11/24, 21:15:28:178 UTC] 00000029 com.ibm.ws.webcontainer.osgi.webapp.WebGroup                 I SRVE0169I: Loading Web Module: Liberty Project.
>     [9/11/24, 21:15:28:187 UTC] 00000029 com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module Liberty Project has been bound to default_host.
>     [9/11/24, 21:15:28:188 UTC] 00000029 com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://mac-1726079118840.local:9080/
>     [9/11/24, 21:15:28:216 UTC] 0000002c com.ibm.ws.session.WASSessionCore                            I SESN0176I: A new session context will be created for application key default_host/
>     [9/11/24, 21:15:28:219 UTC] 0000002c com.ibm.ws.util                                              I SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
>     [9/11/24, 21:15:28:361 UTC] 0000002c com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0001I: Application singleModMavenMP started in 3.876 seconds.
>     [9/11/24, 21:15:28:419 UTC] 00000028 com.ibm.ws.tcpchannel.internal.TCPPort                       I CWWKO0219I: TCP Channel defaultHttpEndpoint has been started and is now listening for requests on host *  (IPv6) port 9080.
>     [9/11/24, 21:15:28:529 UTC] 00000028 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0012I: The server installed the following features: [cdi-3.0, concurrent-2.0, jndi-1.0, json-1.0, jsonb-2.0, jsonp-2.0, mpConfig-3.0, mpHealth-4.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0].
>     [9/11/24, 21:15:28:552 UTC] 00000028 com.ibm.ws.kernel.feature.internal.FeatureManager            I CWWKF0008I: Feature update completed in 12.849 seconds.
>     [9/11/24, 21:15:28:554 UTC] 00000028 com.ibm.ws.kernel.feature.internal.FeatureManager            A CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 22.215 seconds.
>     [9/11/24, 21:15:28:805 UTC] 00000029 com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator          I SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/logs/state/plugin-cfg.xml.
>     [9/11/24, 21:15:29:773 UTC] 0000002c org.jboss.resteasy.resteasy_jaxrs.i18n                       I RESTEASY002225: Deploying jakarta.ws.rs.core.Application: class io.openliberty.sample.StarterApplication$Proxy$_$$_WeldClientProxy
>     [9/11/24, 21:15:30:140 UTC] 0000002c com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [singleModMavenMP] [/] [io.openliberty.sample.StarterApplication]: Initialization successful.
>     [9/11/24, 21:15:39:843 UTC] 0000002c com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0017I: Web application removed (default_host): http://mac-1726079118840.local:9080/
>     [9/11/24, 21:15:39:871 UTC] 0000002c com.ibm.ws.webcontainer.servlet                              I SRVE0253I: [singleModMavenMP] [/] [io.openliberty.sample.StarterApplication]: Destroy successful.
>     [9/11/24, 21:15:41:435 UTC] 0000002c com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0009I: The application singleModMavenMP has stopped successfully.
>     [9/11/24, 21:15:41:523 UTC] 0000002c com.ibm.ws.app.manager.AppMessageHelper                      I CWWKZ0018I: Starting application singleModMavenMP.
>     [9/11/24, 21:15:41:524 UTC] 0000002c bm.ws.app.manager.war.internal.WARDeployedAppInfoFactoryImpl I CWWKZ0134I: The singleModMavenMP application is using the loose application definition at the /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/apps/singleModMavenMP.war.xml location.
>     [9/11/24, 21:15:42:216 UTC] 00000029 com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator          I SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/logs/state/plugin-cfg.xml.
>     [9/11/24, 21:15:47:852 UTC] 0000002c com.ibm.ws.webcontainer.osgi.webapp.WebGroup                 I SRVE0169I: Loading Web Module: Liberty Project.
>     [9/11/24, 21:15:47:871 UTC] 0000002c com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module Liberty Project has been bound to default_host.
>     [9/11/24, 21:15:47:875 UTC] 0000002c com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://mac-1726079118840.local:9080/
>     [9/11/24, 21:15:47:879 UTC] 00000028 com.ibm.ws.session.WASSessionCore                            I SESN0176I: A new session context will be created for application key default_host/
>     [9/11/24, 21:15:47:880 UTC] 00000028 com.ibm.ws.util                                              I SESN0172I: The session manager is using the Java default SecureRandom implementation for session ID generation.
>     [9/11/24, 21:15:47:920 UTC] 0000002c com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0003I: The application singleModMavenMP updated in 6.397 seconds.
>     [9/11/24, 21:15:48:173 UTC] 0000002b com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator          I SRVE9103I: A configuration file for a web server plugin was automatically generated for this server at /Users/runner/work/liberty-tools-intellij/liberty-tools-intellij/liberty-tools-intellij/src/test/resources/projects/maven/singleModMavenMP/target/liberty/wlp/usr/servers/defaultServer/logs/state/plugin-cfg.xml.
>     [9/11/24, 21:15:48:916 UTC] 00000028 org.jboss.resteasy.resteasy_jaxrs.i18n                       I RESTEASY002225: Deploying jakarta.ws.rs.core.Application: class io.openliberty.sample.StarterApplication$Proxy$_$$_WeldClientProxy
>     [9/11/24, 21:15:48:947 UTC] 00000028 com.ibm.ws.webcontainer.servlet                              I SRVE0242I: [singleModMavenMP] [/] [io.openliberty.sample.StarterApplication]: Initialization successful.
>     [9/11/24, 21:15:57:054 UTC] 00000019 com.ibm.ws.kernel.launch.internal.ServerCommandListener      A CWWKE0055I: Server shutdown requested on Wednesday, September 11, 2024 at 9:15 PM. The server defaultServer is shutting down.
>     [9/11/24, 21:15:57:108 UTC] 0000003d com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  A CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
>     [9/11/24, 21:15:57:192 UTC] 0000002a com.ibm.ws.tcpchannel.internal.TCPChannel                    I CWWKO0220I: TCP Channel defaultHttpEndpoint has stopped listening for requests on host *  (IPv6) port 9080.
>     [9/11/24, 21:15:57:230 UTC] 0000002a com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0017I: Web application removed (default_host): http://mac-1726079118840.local:9080/health/
>     [9/11/24, 21:15:57:231 UTC] 0000002a com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0017I: Web application removed (default_host): http://mac-1726079118840.local:9080/
>     [9/11/24, 21:15:58:279 UTC] 0000003d com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  I CWWKE1101I: Server quiesce complete.
>     [9/11/24, 21:15:58:458 UTC] 0000003b com.ibm.ws.webcontainer.servlet                              I SRVE0253I: [singleModMavenMP] [/] [io.openliberty.sample.StarterApplication]: Destroy successful.
>     [9/11/24, 21:15:58:496 UTC] 0000003b com.ibm.ws.app.manager.AppMessageHelper                      A CWWKZ0009I: The application singleModMavenMP has stopped successfully.
>     [9/11/24, 21:15:58:545 UTC] 0000003d com.ibm.ws.webcontainer.servlet                              I SRVE0253I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckStartupServlet]: Destroy successful.
>     [9/11/24, 21:15:58:545 UTC] 0000003d com.ibm.ws.webcontainer.servlet                              I SRVE0253I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckReadinessServlet]: Destroy successful.
>     [9/11/24, 21:15:58:546 UTC] 0000003d com.ibm.ws.webcontainer.servlet                              I SRVE0253I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckLivenessServlet]: Destroy successful.
>     [9/11/24, 21:15:58:546 UTC] 0000003d com.ibm.ws.webcontainer.servlet                              I SRVE0253I: [io.openliberty.microprofile.health.3.1.internal.jakarta] [/health] [HealthCheckServlet]: Destroy successful.
>     [9/11/24, 21:16:00:191 UTC] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0036I: The server defaultServer stopped after 53.852 seconds.
>     ---------------------------------------------------------------------
>     INFO: 2024-09-11T21:23:08.223547: MavenSingleModMPProjectTest.testRunTestsActionUsingSearch(). Exit

**Comment by TrevCraw** [comment]
Need to determine if this failure is still happening and how often.

**Comment by vaisakhkannan** [comment]
I found this issue in one Cron Job build :  https://github.com/vaisakhkannan/liberty-tools-intellij/actions/runs/13026221632/job/36335699554

https://github.com/user-attachments/assets/04e7991b-3ca3-46b7-a8e3-b6939215c631

I couldn't find this issue in other Cron Job builds

**Comment by vaisakhkannan** [comment]
Found this in one PR build https://github.com/OpenLiberty/liberty-tools-intellij/actions/runs/13300707735/job/37141959733?pr=1272
